### ISSUE TITLE
Problem with one of the tests in unsupported testbench

### ISSUE THREAD

**Issue by guigzzz** [HPCE/hpce-2017-cw4#22]
One of the tests in your testbench checks whether the results for simple and naive_par_for are different. 
The problem with this test is that it sometimes passes and sometimes fails due to the naive_par_for version being inherently non-deterministic. Using a 1M problem size like the output text says instead of 64k should drastically increase the chance of naive being different from simple

I also think there's a mistake with the very last test when comparing the simple and par_for_clustered implementations. The test says that it is a 1M test however the `random64k.bin` is used. Changing this test to use `random1M.bin` and changing the time for the simple algorithm to use a data size of 1M makes this test pass. While using a problem size of 64k causes it to fail on my laptop (`simple:` 0.17s vs `par_for_clustered:` 0.11s for 64K and `simple:` 8.52 vs `par_for_clustered:` 2.18 for 1M)

Replacing from line 430 in `test.sh` with the following should fix these issues
```
timeit "w/random64K.bin" "bin/run_network w/n2048.bin:simple" "w/n2048_ref.bin";
TIME_SIMPLE=$foo;

timeit "w/random1M.bin" "bin/run_network w/n2048.bin:simple" "w/n2048_ref_1M.bin";
TIME_SIMPLE_1M=$foo;


timeit "w/random1M.bin" "bin/run_network w/n2048.bin:par_for_naive" "w/n2048_naive.bin";
TIME_NAIVE=$foo;

test_command_and_output "true" "$TIME_SIMPLE < 1.5 MULT $TIME_NAIVE" "For 1M input, check time for simple ($TIME_SIMPLE) is less than 1.5 x par_for_naive ($TIME_NAIVE)"

test_files_differ "w/n2048_ref_1M.bin" "w/n2048_naive.bin" \
	"Check simple version against par_for_naive (should be wrong)"


timeit "w/random64K.bin" "bin/run_network w/n2048.bin:par_for_atomic" "w/n2048_atomic.bin";
TIME_ATOMIC=$foo;

test_command_and_output "true" "1.2 MULT $TIME_SIMPLE < $TIME_ATOMIC" "For 64K input, check time for 1.2 x simple ($TIME_SIMPLE) is less than par_for_atomic ($TIME_ATOMIC)"

test_files_same "w/n2048_ref.bin" "w/n2048_atomic.bin" \
	"Check simple version against par_for_atomic"


timeit "w/random1M.bin" "bin/run_network w/n2048.bin:clustered" "w/n2048_clustered.bin";
TIME_CLUSTERED=$foo;

test_command_and_output "true" "1.2 MULT $TIME_SIMPLE_1M > $TIME_CLUSTERED" "For 1M input, check time for 1.2 x simple ($TIME_SIMPLE_1M) is greater than clustered ($TIME_CLUSTERED)"

test_files_same "w/n2048_ref_1M.bin" "w/n2048_clustered.bin" \
	"Check simple version against clustered"


timeit "w/random1M.bin" "bin/run_network w/n2048.bin:par_for_clustered" "w/n2048_par_for_clustered.bin";
TIME_PAR_FOR_CLUSTERED=$foo;

test_command_and_output "true" "$TIME_SIMPLE_1M > 2.0 MULT $TIME_PAR_FOR_CLUSTERED" "For 1M input, check time for simple ($TIME_SIMPLE_1M) is greater than 2.0 x par_for_clustered ($TIME_PAR_FOR_CLUSTERED)"

test_files_same "w/n2048_ref_1M.bin" "w/n2048_par_for_clustered.bin" \
	"Check simple version against par_for_clustered"
```

**Comment by m8pple** [comment]
I refer you to this part of the CW4 spec:

> Use an AWS c4.8xlarge instance

and this part of the readme on the _unsupported_ scripts:

> They are designed to run only in an environment that I control,
> which is nominally the AWS HPCE AMI or an equivalent 

I'm not sure this quite fits with this statement:

>  While using a problem size of 64k causes it to fail on my laptop

How many cores does your laptop have, and what is it's cache hierarchy?
The target machine is a 36 thread server, split across 18 cores, so the
probability of seeing corruptions is _exceptionally_ high in that scenario.

(As an extra data-point that you don't currently have, consider that every
single submission from last year (the first year I used this CW) passed that test,
with not a single failure.)

For the last test that fails, this doesn't actually appear in the version I've been
testing. I think I just uncommented and modified it while playing around
last week, as it doesn't appear in any of the logs from last year, nor in the
pre-runs I've been doing last week. Probably I copied it off my laptop repo
which was not in sync. I refer you to this:

> They are also likely to drift out of sync with the master scripts

I've been putting more logging into the cw4 tests (to give more info back),
so they have already drifted.

So what you describe is indeed a bug, but I don't think it will appear in the
actual output that people see.

That said, thanks for offering potential solutions, as they might have been
things I didn't know about.

**Comment by guigzzz** [comment]
ah I realise I should have read that documentation before posting, Sorry. Laptop is 4 core 8 thread but compared to 18/36 that's peanuts. And I guess that the last test being commented out in your test means that this is a non issue. Everything resolved then
