### ISSUE TITLE
Clarification of sustained bandwidth

### ISSUE THREAD

**Issue by JunShern** [HPCE/hpce-2017-cw4#31]
Hi,

In generating the `pipeline_p_vs_bandwidth` plot, you ask us to measure "sustained bandwidth (i.e. bytes/sec". Can I just clarify whether you intend for us to measure the 

1. Number of input bytes (i.e. 1048576) / runtime (measured using `time`), OR

2. The bandwidth of data flowing out of the pipeline as measured using `cat w/random1M.bin | scripts/run_n512_P1.sh | pv > /dev/null`, OR

3. The bandwidth of data flowing elsewhere in the pipeline, for example `cat w/random1M.bin | pv | scripts/run_n512_P1.sh > /dev/null`

And what in particular makes any of these options a better measure for performance than others?

Thanks!

**Comment by m8pple** [comment]
Interesting question.

First, if we consider options 2 and 3, would you _expect_ to see any differences - if so, why?
There is then the question of whether any actual differences do appear...

Option 1 it is clearly different in some way, as it is looking at the bandwidth achieved
over the entire stream, so if you look at measuring over a whole interval, we could do:
```
N="100 1000 10000 100000 1000000 10000000 100000000 1000000000 10000000000";
for i in $N; do
  time head -c $i /dev/urandom > /dev/null ;
done
```
Where do we start to see a good approximation of sustained bandwidth coming,
if we take `time / bytes` ?

In contrast, `pv` is trying to estimate the _instantaneous_ bandwidth at any
point in time. `pv` actually has an option (`-i`) to change the estimation interval,
so you might like to try looking at:
```
cat /dev/urandom   |  pv -i 0.1    >/dev/null
```
versus:
```
cat /dev/urandom   |  pv -i 1.0    >/dev/null
```
Which one is a better measure of sustained bandwidth?


So to (sort of) answer your question: all three of the approaches should asymptotically
result in exactly the same sustained bandwidth. But it needs to be the asymptote
as the amount of data is increased, so if you're seeing very different bandwidths between
the methods, I'd be questioning this part:
```
cat w/random1M.bin
```

**Comment by JunShern** [comment]
Thanks for the comprehensive reply! That helped me figure out what I want to do for the data plots, so I'll close this issue.
