### ISSUE TITLE
What is 'n'

### ISSUE THREAD

**Issue by janscholten** [HPCE/hpce-2017-cw4#33]
For the last task of cw4, I am creating a bunch of NNs of varying size, i.e.  `n=nIn-nOut` 
However my friend picked his favorite (square) net with equal number of inputs and outputs, and then evaluates its performance for different `n`, where `n` is the size of the random vector fed into his NN.

Who is complying to the exercise? We are not sure.

**Comment by m8pple** [comment]
I was thinking of the latter, so `n==nIn==nOut`, with square nets.

However, your interpretation is actually kind of interesting, as it is going
to test something quite different. If you've already done the experiment,
then don't worry about redoing it - just make sure it is reasonably clear
on the graph what n means - presumably you need to fix one of nIn or
nOut?

I have to heck a random subset of the submitted graphs, so from my
point of view it is fun to find the situations where someone has come up
with a different interpretation (though that doesn't mean everyone
should do random graphs...)

**Comment by janscholten** [comment]
thank you for clarifying
