### ISSUE TITLE
Failing shell scripts due to engine 'auto' 

### ISSUE THREAD

**Issue by Afrazinator** [HPCE/hpce-2017-cw4#35]
Hi, I seem to be failing every pipeline script in the logs due to some unknown engine selection:
```
Loading layer 1 from file w/n512_00.bin using engine auto
ERROR : Unknown engine 'auto'
```

Is anyone else having this problem?

**Comment by AlanDu50** [comment]
In **src/layers/layer_factory.cpp**, you probably commented out or deleted:
```
}else if(layerEngine=="auto"){
        return CreateSimpleLayer(nIn,nOut,synapses);
```

**Comment by Afrazinator** [comment]
That was it, cheers!
