### ISSUE TITLE
Amazon forgets to include promo code in student email

### ISSUE THREAD

**Issue by natoucs** [HPCE/hpce-2017-cw4#36]
"Dear Nathan,
Congratulations!

Your AWS Educate application has been approved. As a member of the AWS Educate program, you will gain access to the benefits listed below:

AWS Educate Student Portal 
The AWS Educate Student Portal is the hub for AWS Educate students around the world to find AWS content to help with classwork, connect to self-paced labs and training resources.

Click here to set your password / login to the AWS Educate Student Portal. After logging in, click AWS Account at the top of the page to access AWS services, whether you entered an AWS ID or selected Starter Account on your application. Note that Starter Accounts are not eligible for AWS Free Tier.

Bookmark the AWS Educate Student Portal for easy access, or click here to sign in directly.

You can access a video walk-through of the AWS Educate Student portal here. 

Free AWS Essentials Training 
To access our foundational AWS Essentials online learning class for free and find other self-paced labs, you must have either and AWS account or an Amazon ID.

If you have an AWS account, sign in and click here to receive these benefits.
If you do not have an AWS account, click here and follow the instructions to create an Amazon ID to access these benefits.
Once you access the Training and Certification portal, click "Find Training" and search for "Technical" to easily locate and enroll in AWS Technical Essentials on-line training. You can access AWS training any time after setting up your account by clicking here.

Thank you again for participating in AWS Educate and we hope you enjoy the program!

The AWS Educate Team"

My friend had exactly the same email but the promo code was included just above `free aws essentials training.

Someone told me he contacted the support center about this and he got credited the amount a few days after.

**Comment by davidanderle** [comment]
I have the same issue here.. Not getting an ID, I logged into the _AWS Educate Student Portal_ and followed the instructions, but AWS did not let me run the _c4.8xlarge_ instance. I then stopped the lab on _AWS Educate Starter Account 75_ to try things from the beginning, and now it does not even let me start the lab again.. I must be missing some huge piece of information here, and the support hasn't reacted to my issue for like 30h now.

**Comment by davidanderle** [comment]
Got it working. This works even if you've already registered with your ICL email address.
1, Register for the _GitHub Student Developer Pack_ at [https://education.github.com/pack/offers](url)
2, Follow the _Unique Link_ provided by _GitHub Student Developer Pack_ to _AWS Educate_
3, Fill in stuff using your _ICL email_ address (luckily, it accepts your short email address if you've already registered with your long one, and hopefully vice versa), and **keep the tab open when prompted for 
 Account ID** 
4, Go to your AWS account that you registered with for a free trial (mine is a simple gmail account)
5, Click your account name on top right -> _My Account_ -> copy your **Account ID** to clipboard
6, Go back to the AWS Edu tab you kept open and paste your gmail AWS Account ID into the Account ID field
7, Wait for the confirmation emails (mine took 5 sec)
8, Type in the Credit Code (for $150) you get from the email to your gmail AWS  (_My Account_ -> _Credits_)

**Comment by natoucs** [comment]
Works great, thanks @davidanderle !
